### ISSUE TITLE
Implement Schematic for updating angular.json

### ISSUE THREAD

**Issue by kyliau** [DevExpress/angular-testcafe#63]
Please consider adding an Angular schematic to
1. automatically update `angular.json` to use the TestCafe builder
2. generate e2e example to help users get started

If support for `ng-add` is implemented, it'll help users adopt TestCafe more easily.

For reference, please check out the schematic for [Protractor](https://github.com/angular/angular-cli/tree/master/packages/schematics/angular/e2e) and [WebdriverIO](https://github.com/webdriverio/webdriverio-schematics/tree/main/src/schematics).

Once the schematic is available, we'll add TestCafe to the Angular CLI (see https://github.com/angular/angular-cli/pull/20503). Please feel free to reach out if you have any questions!

**Comment by timnederhoff** [comment]
Hi @kyliau I think that is a good idea, let me work on it. Keep you posted
