### ISSUE TITLE
Nrwl nx plugin

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [DevExpress/angular-testcafe#70]
Hi, please consider building a plugin to Nrwl NX https://github.com/nrwl/nx.

**Comment by kbmmdwork** [comment]
+1

**Comment by AlexKamaev** [comment]
Thank you for pointing us to that repository. At this moment, we've already planned our roadmap, so we will continue to work on our planned features in the nearest future. We can return to this question during further planning.
