### ISSUE TITLE
Add support for window-size

### ISSUE THREAD

**Issue by wlucha** [DevExpress/angular-testcafe#82]
Please add support for the "window-size" parameter.

**Comment by aleks-pro** [comment]
Hello @wlucha ,

Your suggestion is not clear. Please describe your usage scenario in greater detail.

**Comment by aleks-pro** [comment]
I'm afraid your suggestion is still not clear. Please refer to [this](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+enhancement&template=feature_request.yaml) template to describe it in detail.
