### ISSUE TITLE
Release for Angular 13 support

### ISSUE THREAD

**Issue by Bjeaurn** [DevExpress/angular-testcafe#83]
Hi, I've noticed that in #79 the problem with the changed Schema was fixed. However, this fix was merged, it was never released. 

Can we organize a new release?

**Comment by felis2803** [comment]
Hello @Bjeaurn,

Thanks for reminding us of this. We will do it.

**Comment by AndreyBelym** [comment]
`angular-testcafe@3.0.0` is published now, thank you for your patience.
